version: "3.4"

services:
    creditboss-api:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: creditboss-api
        ports:
          - "8080:80"
        depends_on:
          - creditboss-db

    creditboss-db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        container_name: creditboss-db
        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"

